kind: Pelorus
apiVersion: charts.pelorus.dora-metrics.io/v1alpha1
metadata:
  name: pelorus-instance
  namespace: pelorus
spec:
  exporters:
    instances:
    - app_name: deploytime-exporter
      exporter_type: deploytime
      extraEnv:
      - name: NAMESPACES
        value: test-app
    - app_name: committime-exporter
      exporter_type: committime
      extraEnv:
      - name: NAMESPACES
        value: test-app
    - app_name: failure-exporter-pelorus
      exporter_type: failure
      env_from_secrets:
      - jira-secret
      extraEnv:
      - name: SERVER
        value: https://poslavskyy.atlassian.net/
      - name: PROJECTS
        value: Pelorus
    - app_name: webhook-exporter
      exporter_type: webhook
      extraEnv:
      - name: LOG_LEVEL
        value: debug
  openshift_prometheus_basic_auth_pass: changeme
  openshift_prometheus_htpasswd_auth: 'internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM='
  prometheus_retention: 1y
  prometheus_retention_size: 1GB
  prometheus_storage: false
  prometheus_storage_pvc_capacity: 2Gi
  prometheus_storage_pvc_storageclass: gp2
